table DimDate
	lineageTag: 62a3ae73-0502-484f-b2c7-1d6c6c3aad97
	dataCategory: Time

	column DateKey
		dataType: int64
		isHidden
		lineageTag: 537765d5-feee-472e-9143-9cd2c3288ec4
		summarizeBy: none
		sourceColumn: DateKey

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: 2ffe34af-159a-42b4-9ba9-5392cc5f704f
		summarizeBy: none
		sourceColumn: Date

	column DateDatetime
		dataType: dateTime
		isHidden
		lineageTag: 6787646e-c1fd-44e0-a336-b0bb5e0c17a7
		summarizeBy: none
		sourceColumn: DateDatetime

	column CalendarYear
		dataType: int64
		lineageTag: 5685ae68-d897-4883-92df-3c0fb90cc23c
		dataCategory: Years
		summarizeBy: none
		sourceColumn: CalendarYear

	column CalendarQuarter
		dataType: int64
		lineageTag: a852d8df-6d18-4a5f-a2e7-2ca659033af2
		summarizeBy: none
		sourceColumn: CalendarQuarter

	column CalendarMonth
		dataType: int64
		isHidden
		lineageTag: 44d519e3-e9a5-4e1c-b124-ce65ec79de8f
		summarizeBy: none
		sourceColumn: CalendarMonth

	column MonthName
		dataType: string
		lineageTag: 6be43a82-c7f7-4741-aa78-62d5e30b3330
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: CalendarMonth

	column MonthShort
		dataType: string
		lineageTag: bc44400c-682a-4a46-9d9f-a05143961d3e
		summarizeBy: none
		sourceColumn: MonthShort

	column YearMonth
		dataType: string
		lineageTag: 2b7c55e8-9e61-4af1-88ee-cb77b844ef6b
		summarizeBy: none
		sourceColumn: YearMonth
		sortByColumn: YearMonthSort

	column YearMonthSort
		dataType: int64
		isHidden
		lineageTag: 2aed45c2-03dc-4913-99d6-8baee085f6e7
		summarizeBy: none
		sourceColumn: YearMonthSort

	column YearQuarter
		dataType: string
		lineageTag: cd2b8927-1542-4a18-9a88-8ee4b4d27a12
		summarizeBy: none
		sourceColumn: YearQuarter

	column WeekOfYear
		dataType: int64
		lineageTag: ffdc029c-e2d7-4835-bb6d-f622340d10ec
		summarizeBy: none
		sourceColumn: WeekOfYear

	column IsoYear
		dataType: int64
		isHidden
		lineageTag: 22334198-6b3e-461d-a0fc-8533028fdf53
		summarizeBy: none
		sourceColumn: IsoYear

	column WeekStartDate
		dataType: dateTime
		lineageTag: c48c78f9-a923-4a33-9a20-1394612d9999
		summarizeBy: none
		sourceColumn: WeekStartDate

	column WeekEndDate
		dataType: dateTime
		lineageTag: 5f57b922-23a3-4803-87a8-f73500d30f12
		summarizeBy: none
		sourceColumn: WeekEndDate

	column DayOfMonth
		dataType: int64
		lineageTag: 76e3e065-618d-4412-acae-de6b30af8ac6
		summarizeBy: none
		sourceColumn: DayOfMonth

	column DayOfYear
		dataType: int64
		isHidden
		lineageTag: 390a4741-3b96-45ea-ba5e-fcb56ee34eb4
		summarizeBy: none
		sourceColumn: DayOfYear

	column DayName
		dataType: string
		lineageTag: b622d4df-c01e-4fa2-9261-c1862b2f012d
		summarizeBy: none
		sourceColumn: DayName

	column DayShort
		dataType: string
		lineageTag: 2b73bc9c-952e-42be-9655-c9f35975058c
		summarizeBy: none
		sourceColumn: DayShort

	column DayOfWeek
		dataType: int64
		isHidden
		lineageTag: 982bf814-5e50-49a8-8827-bcd14c4f7774
		summarizeBy: none
		sourceColumn: DayOfWeek

	column IsWeekend
		dataType: boolean
		lineageTag: dbf0040e-dbc3-4734-a8ce-1059ceb6c64e
		summarizeBy: none
		sourceColumn: IsWeekend

	column IsHoliday
		dataType: boolean
		lineageTag: 5c255f9c-b68a-4e07-bf44-87e215b8c03c
		summarizeBy: none
		sourceColumn: IsHoliday

	column HolidayName
		dataType: string
		lineageTag: 45afa606-4c20-4e8c-a532-414994f7280f
		summarizeBy: none
		sourceColumn: HolidayName

	column IsMonthEnd
		dataType: boolean
		lineageTag: 0461ddc8-e09c-4a0c-b4bb-0aee19bc3381
		summarizeBy: none
		sourceColumn: IsMonthEnd

	column IsQuarterEnd
		dataType: boolean
		lineageTag: cb81e8c0-0d98-49f8-b61f-91e597dd2821
		summarizeBy: none
		sourceColumn: IsQuarterEnd

	column IsYearEnd
		dataType: boolean
		lineageTag: cc01fed5-db8a-4b47-8df6-a52b320597a7
		summarizeBy: none
		sourceColumn: IsYearEnd

	column DaysInMonth
		dataType: int64
		isHidden
		lineageTag: 16e054cd-a35a-4ab5-9d39-4cc2a10b15d2
		summarizeBy: none
		sourceColumn: DaysInMonth

	column FiscalYear
		dataType: int64
		lineageTag: b099a969-5b2b-4b16-86cb-96bd39e10a05
		summarizeBy: none
		sourceColumn: FiscalYear

	column FiscalQuarter
		dataType: int64
		lineageTag: e1faca2b-ee47-4123-9df8-6750ba28d7eb
		summarizeBy: none
		sourceColumn: FiscalQuarter

	column FiscalMonth
		dataType: int64
		isHidden
		lineageTag: e734ebb9-b227-4795-9fc6-376d8810d645
		summarizeBy: none
		sourceColumn: FiscalMonth

	column Season
		dataType: string
		lineageTag: 589f418a-88ca-4342-85ce-c79ce183752e
		summarizeBy: none
		sourceColumn: Season

	column IsPartialDatacoYear
		dataType: boolean
		lineageTag: 106fa0c1-50b3-4d2d-b38b-4db468cc402d
		summarizeBy: none
		sourceColumn: IsPartialDatacoYear

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents(pCuratedFolder & "\dim_date.parquet")),
				    Renamed = Table.RenameColumns(Source, {{"date_key", "DateKey"}, {"date", "Date"}, {"date_datetime", "DateDatetime"}, {"calendar_year", "CalendarYear"}, {"calendar_quarter", "CalendarQuarter"}, {"calendar_month", "CalendarMonth"}, {"month_name", "MonthName"}, {"month_short", "MonthShort"}, {"year_month", "YearMonth"}, {"year_month_sort", "YearMonthSort"}, {"year_quarter", "YearQuarter"}, {"week_of_year", "WeekOfYear"}, {"iso_year", "IsoYear"}, {"week_start_date", "WeekStartDate"}, {"week_end_date", "WeekEndDate"}, {"day_of_month", "DayOfMonth"}, {"day_of_year", "DayOfYear"}, {"day_name", "DayName"}, {"day_short", "DayShort"}, {"day_of_week", "DayOfWeek"}, {"is_weekend", "IsWeekend"}, {"is_holiday", "IsHoliday"}, {"holiday_name", "HolidayName"}, {"is_month_end", "IsMonthEnd"}, {"is_quarter_end", "IsQuarterEnd"}, {"is_year_end", "IsYearEnd"}, {"days_in_month", "DaysInMonth"}, {"fiscal_year", "FiscalYear"}, {"fiscal_quarter", "FiscalQuarter"}, {"fiscal_month", "FiscalMonth"}, {"season", "Season"}, {"is_partial_dataco_year", "IsPartialDatacoYear"}}, MissingField.Ignore),
				    Typed = Table.TransformColumnTypes(Renamed, {{"DateKey", Int64.Type}, {"Date", type datetime}, {"DateDatetime", type datetime}, {"CalendarYear", Int64.Type}, {"CalendarQuarter", Int64.Type}, {"CalendarMonth", Int64.Type}, {"MonthName", type text}, {"MonthShort", type text}, {"YearMonth", type text}, {"YearMonthSort", Int64.Type}, {"YearQuarter", type text}, {"WeekOfYear", Int64.Type}, {"IsoYear", Int64.Type}, {"WeekStartDate", type datetime}, {"WeekEndDate", type datetime}, {"DayOfMonth", Int64.Type}, {"DayOfYear", Int64.Type}, {"DayName", type text}, {"DayShort", type text}, {"DayOfWeek", Int64.Type}, {"IsWeekend", type logical}, {"IsHoliday", type logical}, {"HolidayName", type text}, {"IsMonthEnd", type logical}, {"IsQuarterEnd", type logical}, {"IsYearEnd", type logical}, {"DaysInMonth", Int64.Type}, {"FiscalYear", Int64.Type}, {"FiscalQuarter", Int64.Type}, {"FiscalMonth", Int64.Type}, {"Season", type text}, {"IsPartialDatacoYear", type logical}})
				in
				    Typed

